name: Nuget Package Deploy

on:
    push:
        paths:
        - 'src/examples/messages/c#/messages/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.1.100
            - name: Build with dotnet
              run: dotnet build --configuration Release
              working-directory: ./src/examples/messages/c#/messages
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Pack nuget Package
              run: dotnet pack --configuration
              working-directory: ./src/examples/messages/c#/messages
            - name: Push package to nuget
              run: dotnet nuget push **/*.nupkg
                        --api-key ${{ secrets.GDS_MESSAGES_NUGET_DEPLOY_KEY	}}
                        --source https://api.nuget.org/v3/index.json
